import 'dotenv/config'

export const env = {
  MONGODB_URI: process.env.MONGODB_URI,

  WHITELIST_DOMAINS: process.env.WHITELIST_DOMAINS,

  LOCAL_DEV_APP_HOST: process.env.LOCAL_DEV_APP_HOST,
  LOCAL_DEV_APP_PORT: process.env.LOCAL_DEV_APP_PORT,

  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  CLERK_SINGING_KEY: process.env.CLERK_SINGING_KEY,
  BUILD_MODE: process.env.BUILD_MODE,

  AUTHOR : process.env.AUTHOR,
  ADMIN_PASSWORD : process.env.ADMIN_PASSWORD,

  WEBSITE_DOMAIN_DEVELOPMENT: process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION: process.env.WEBSITE_DOMAIN_PRODUCTION,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  TWILIO_ACCOUNT_SID : process.env.TWILIO_ACCOUNT_SID,
  TWILIO_API_KEY_SID : process.env.TWILIO_API_KEY_SID,
  TWILIO_API_KEY_SECRET : process.env.TWILIO_API_KEY_SECRET,
  TWILIO_AUTH_TOKEN : process.env.TWILIO_AUTH_TOKEN
}